version: '3'

services:
  front:
    build:
      context: ../../
      dockerfile: docker/docker-compose/front.dockerfile
    container_name: 'contact-front'
    ports:
      - 8080:80
    depends_on:
      - api

  api:
    build:
      context: ../../
      dockerfile: docker/docker-compose/api.dockerfile
    container_name: 'contact-api'
    ports:
      - 5000:8000
