env:
    browser: true
    es2021: true
extends:
    - "eslint:recommended"
    - "plugin:react/recommended"
    - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 12
    sourceType: module
plugins:
    - react
    - "@typescript-eslint"
rules: {
        # Disable warning on 'any' on every file, it's easier until most of them
        # have been replaced for more precise types.
        "@typescript-eslint/no-explicit-any": "off",
    }
settings:
    react:
        version: "detect"
